datasets:
  sflexneri:
    guide-strain: "NC_004337.2"

pangraph:
  build-opt: "--circular -k minimap2 -s 20 -a 100 -b 5 -l 100"
  polish-opt: "-c"

backbone-joints:
  len-thr: 500
  build-opt: "-k minimap2 -s 20 -a 100 -b 5 -l 100"
  polish-opt: "-c"

resistance:
  id_threshold: 0.95
