datasets:
  sflexneri_test:
    guide-strain: "NC_004337.2"
  paeruginosa_ST235:
    guide-strain: "NC_017549.1"
  # psyr_1:
  #   guide-strain: "208-2"
  #   corefilt-window: 100
  #   corefilt-snps: 3
  # psyr_2:
  #   guide-strain: "174-1"
  #   corefilt-window: 100
  #   corefilt-snps: 3
  # psyr_3:
  #   guide-strain: "174-1"
  #   corefilt-window: 100
  #   corefilt-snps: 3
  # psyr_psa3pan:
  #   guide-strain: "157-1"
  #   corefilt-window: 100
  #   corefilt-snps: 3
  # psyr_psa3pan_res:
  #   guide-strain: "157-1"
  #   corefilt-window: 100
  #   corefilt-snps: 3
  # psyr_pth:
  #   guide-strain: "218-2"
  #   corefilt-window: 100
  #   corefilt-snps: 3
  # psyr_psa16:
  #   guide-strain: "280-5"
  #   corefilt-window: 100
  #   corefilt-snps: 3
  # psyr_psa2:
  #   guide-strain: "40-2"
  #   corefilt-window: 100
  #   corefilt-snps: 3
  # psyr_psa32:
  #   guide-strain: "40-2"
  #   corefilt-window: 100
  #   corefilt-snps: 3
  # hpylori_none:
  #   guide-strain: "NZ_CP036387.1"
  # hpylori_ST3020:
  #   guide-strain: "NZ_CP024072.1"
  # spneumoniae_180:
  #   guide-strain: "NZ_CP090884.1"
  # spyogenes_28:
  #   guide-strain: "NZ_CP040997.1"
  # spyogenes_52:
  #   guide-strain: "NZ_CP031632.1"
  # bpertussis_ST83:
  #   guide-strain: "NZ_CP026447.1"
  # ecoli_ST69:
  #   guide-strain: "NZ_CP102488.1"
  # ecoli_ST73:
  #   guide-strain: "NZ_CP051263.1"
  # ecoli_ST95:
  #   guide-strain: "NZ_CP043950.1"
  # ecoli_ST131:
  #   guide-strain: "NZ_CP096110.2"
  # kpneumoniae_ST14:
  #   guide-strain: "NZ_CP115707.1"
  # kpneumoniae_ST15:
  #   guide-strain: "NZ_CP100098.1"
  # kpneumoniae_ST17:
  #   guide-strain: "NZ_CP125180.1"
  # kpneumoniae_ST258:
  #   guide-strain: "NZ_CP043047.1"
  # kpneumoniae_ST512:
  #   guide-strain: "NZ_CP090626.1"
  # mtuberculosis_ST276:
  #   guide-strain: "NZ_CP002883.1"
  # saureus_ST1:
  #   guide-strain: "NZ_CP019574.1"
  # saureus_ST5:
  #   guide-strain: "NC_002758.2"
  # paeruginosa_ST111:
  #   guide-strain: "NZ_CP086213.1"
  # paeruginosa_ST463:
  #   guide-strain: "NZ_CP064393.1"

pangraph:
  build-opt: "--circular -k minimap2 -s 20 -a 100 -b 5 -l 100"
  polish-opt: "-c"

backbone-joints:
  len-thr: 500
  build-opt: "-k minimap2 -s 20 -a 100 -b 5 -l 100"
  polish-opt: "-c"

resistance:
  id_threshold: 0.95
