datasets:
  saureus_S1:
    chromosomes: "config/datasets/saureus_S1/assembly_to_chrom.tsv"
    excluded: "config/datasets/saureus_S1/excluded.txt"
    guide-strain: "NZ_CP019574.1"
    pang-build-opt: "--circular -k minimap2 -s 20 -a 100 -b 5 -l 100"
pangraph:
  polish-options: "-c"

backbone-joints:
  len-thr: 500
  build-opt: "-k minimap2 -s 20 -a 100 -b 5 -l 100"
  polish-opt: "-c"

resistance:
  id_threshold: 0.95
